### ISSUE TITLE
Get a book on Neural Networking.

### ISSUE THREAD

**Issue by codbellamy** [codbellamy/Directed-Study#3]

**Comment by codbellamy** [comment]
[neuralnetworksanddeeplearning.pdf](https://github.com/codbellamy/Directed-Study/files/4061879/neuralnetworksanddeeplearning.pdf)

Looking into this text.

**Comment by ifrommer** [comment]
This is the book LCDR Williams recommended:
[https://www.amazon.com/Make-Your-Own-Neural-Network-ebook/dp/B01EER4Z4G](https://www.amazon.com/Make-Your-Own-Neural-Network-ebook/dp/B01EER4Z4G)

**Comment by codbellamy** [comment]
Justin and I have decided to go with both books. The PDF will be used as a reference and to supplement the material covered in the _Make Your Own Neural Netowrk_ book.
